### PR TITLE
React capstone project -Metrics webapp pull request

### PR DESCRIPTION
**Pull request by theresetuyi**
## React capstone project - Metrics webapp
-Use React documentation.
-Use React components.
-Use React props.
-Use React Router.
-Connect React and Redux.
-Handle events in a React app.
-Add tests with a React testing library.
-Use styles in a React app.
-Use React life cycle methods.
-Apply React best practices and language style guides in code.
-Use store, actions, and reducers in React

### CODE REVIEW

**Review by andersonlebon — COMMENTED** [review]
## Hi @theresetuyi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain the requested changes of the previous reviewer, kindly submit a valid PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by theresetuyi** [comment]
I don't understand why my PR was Invalid ?

**Comment by alexander16108** [comment]
Hi @theresetuyi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow the correct giitflow 
you ought to create a pull request from the dev branch to merge into the main branch as it is your final version of the project. I'm very sorry for the inconvenience

** in order to solve this dilemma I suggest you merge this PR to the dev branch and create a new pr from the dev branch to merge to main
`merge 2 commits into [main]() from [dev]()`

#### side note please do not delete any branch or start over 
Good Luck 🍀 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by theresetuyi** [comment]
I did sevel time and my PR was rejected

**Comment by theresetuyi** [comment]
First I marge all branch in main and create anather branch reviewer reject
my submission, I dicide to delete all thing and start again and now still
rejected so what can I do now?maybe I have to give up

**Review by shella12 — APPROVED** [review]
Hi @theresetuyi, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Tests are passing ✔️ 
- Site is deployed 🚀 
- Great design implementation 👍 
- Used DUCK pattern 🦆 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
